### ISSUE TITLE
Take a look at wp-composer

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/composer-managed-wordpress#1]
https://github.com/rxnlabs/wp-composer

**Comment by lkraav** [comment]
Looking at wp-composer last updated 6 y ago, why not refactor this issue towards https://github.com/wecodemore/wpstarter instead?

We are actively riding WPStarter train, it has worked out great, and is activey supported and developed by superman @gmazzap.

Makes sense to avoid reinventing the wheel and collab instead?

**Comment by szepeviktor** [comment]
> Looking at wp-composer last updated 6 y ago

75% of viktor's time goes to learning.

> We are actively riding WPStarter train

@lkraav Look at this fresh paintjob: https://github.com/szepeviktor/composer-managed-wordpress
A slick train 🚅 for you.

And there is a repo for theory too.
https://github.com/szepeviktor/wordpress-website-lifecycle

**Comment by szepeviktor** [comment]
Thank you for sharing wpstarter with me.

What a complexity!
Everything is managed behind the curtain 👉🏻 when there is a problem the wpstarter user will have no knowledge.

**Comment by szepeviktor** [comment]
> I'm an operations person.

... providing premium operations

**Comment by lkraav** [comment]
Sure, whatever works for you. Was hoping to get WPStarter boosted with your skill and knowledge if it was a better fit. I'll be in touch about your services in email.

**Comment by szepeviktor** [comment]
For me it is highly beneficial to look at WPStarter. It helps me describe my services.
@lkraav Thank you for that!
That is a years-long problem for me.

**Comment by gmazzap** [comment]
Thanks for the "superman" @lkraav :)

I just wanted to say that [Inpsyde](https://inpsyde.com/en/) sponsors the development of that thing.
And at Inpsyde, it is used to build *very* complex sites.

@szepeviktor not "pushing" anything here, but let me comment on some of the things you wrote.

> What a complexity!

Indeed. WP Starter started [8 years ago](https://github.com/wecodemore/wpstarter/tree/75f423e1e463c366b88bd1b2c4e09facc506c2f2) as a much simpler thing.
The complexity has been added along the way to address issues. Guess what, complex problems can not be solved in a simple way :)
And make an extensible and configurable Composer (v1 & v2) Plugin for WordPress capable of handling a wide range of the mad stuff WordPress people do... well, it _is_ complex.
If you also want to support environment variables and env files, well, complexity increases.

---

> WP Starter dropins could be simply symlinks

They are symlinks (or copies if your system does not support them). But if they live in separate repositories (e.g. if you want to share across projects), you first need to download them and then symlink in the proper folder (wp-content).

But also the wp-content folder can be customized in the project's `composer.json`  (if you use the most popular Composer installers for WP). And, of course, you can't rely on WP constants to determine the correct path while installing WP via Composer.

And if this is not complex enough yet, some plugins in the WP ecosystem are both plugins _and_ MU drop-ins.
Not to mention that external repositories can contain one or many drop-ins.
Some will not support Composer (no `composer.json` in the root).

As you can see, _"simply"_ is a word that can be rarely used when talking about making Composer work with the WordPress ecosystem.

---

> WP Starter supports PHP 7.1, for me PHP 7.4 is a pain but also a must for the current WordPress ecosystem

Not sure what you mean by this. WP Starter supports PHP 7.1 as the minimum version, you're free to use 7.4, 8.0, or 8.1. WordPress supports 5.6, but the minimum version is unrelevant. What matters IMO is the most recent version it is compatible with.
And because WP Starter is meant to be required via Composer, in your root `composer.json`, you can require whatever PHP version you like, well, whatever 7.1+.

---

> WP Starter uses psalm, and you may know szepeviktor/phpstan-WordPress with 1.1 M downloads

WP Starter uses Psalm for _its own code_, which is *not* WordPress code (mostly pure PHP, dependency only on Composer and dotenv). So "phpstan-wordpress" is unrelevant to WP Starter.
People that use WP Starter for their WP projects can use phpstan, phpstan-wordpress, or whatever they like. Being Psalm a dev dependency, it will not be pulled if you require WP Starter (unlike other projects with similar scope, WP Starter is required as a Composer dependency, hence upgradable besides having independent dev dependencies).


> WP Starter tests are failing a year ago

Tests are _not_ failing, CI is failing :) And yes, I have to fix it, and my plan is to fix it next I get some more sponsored time to work on it, which should happen pretty soon.

**Comment by szepeviktor** [comment]
All right - all right @gmazzap!
I do not support projects where it is not possible to clean up things:
- "Composer v1"
- "no composer.json in the root"
- "PHP 7.1"
I know this is not user friendly but I'd like to keep everything simple.
You may tell me that I live in an utopia!
But I can serve only a handful of clients. My dream is to work for a single company.
